### ISSUE TITLE
not going to debuild from source

### ISSUE THREAD

**Issue by cappelikan** [aljex/mainline#9]
Now running lintian mainline_1.0.1ubuntu1_source.changes ...
E: mainline source: build-depends-on-essential-package-without-using-version build-depends: bash
W: mainline source: missing-license-paragraph-in-dep5-copyright gpl-3 (paragraph at line 5)
Finished running lintian.

**Comment by aljex** [comment]
I removed the bash build requires, and tried to add the gpl-3 text, but some part of pbuilder auto-removed it, so I guess since that part was only a warning we just ignore it?
Try it now.

**Comment by cappelikan** [comment]
Ошибка исчезла собралось все великолепно

**Comment by aljex** [comment]
great.
